// =================================
// DATOS DEMO PARA POWERBI - SIN SERVIDOR
// Crear tabla manual para practicar dashboard
// =================================

let
    // Crear tabla de fondos demo directamente en PowerBI
    Source = #table(
        {"PshipID", "FundName", "TotalAssets", "YTDReturn", "Status", "RiskLevel", "AssetClass", "Currency"},
        {
            {1, "Fondo Alpha Equity", 5500000000, 0.128, "Active", "High", "Equity", "CLP"},
            {2, "Fondo Beta Fixed Income", 3200000000, 0.045, "Active", "Low", "Fixed Income", "CLP"},
            {3, "Fondo Gamma Mixed", 4700000000, 0.089, "Active", "Medium", "Mixed", "CLP"},
            {4, "Fondo Delta Real Estate", 2100000000, 0.156, "Active", "High", "Real Estate", "CLP"},
            {5, "Fondo Epsilon Tech", 6800000000, 0.203, "Active", "High", "Equity", "CLP"},
            {6, "Fondo Zeta Conservative", 1900000000, 0.028, "Active", "Low", "Fixed Income", "CLP"},
            {7, "Fondo Eta Growth", 3600000000, 0.174, "Active", "Medium", "Mixed", "CLP"},
            {8, "Fondo Theta Commodity", 1400000000, -0.032, "Active", "High", "Commodity", "CLP"},
            {9, "Fondo Iota Infrastructure", 2800000000, 0.067, "Active", "Medium", "Real Estate", "CLP"},
            {10, "Fondo Kappa International", 4200000000, 0.098, "Active", "Medium", "Mixed", "USD"},
            {11, "Fondo Lambda ESG", 3100000000, 0.112, "Active", "Medium", "Equity", "CLP"},
            {12, "Fondo Mu Dividend", 2700000000, 0.054, "Active", "Low", "Equity", "CLP"},
            {13, "Fondo Nu Aggressive", 5200000000, 0.245, "Active", "High", "Equity", "CLP"},
            {14, "Fondo Xi Balanced", 3900000000, 0.076, "Active", "Medium", "Mixed", "CLP"},
            {15, "Fondo Omicron Value", 2600000000, 0.143, "Active", "Medium", "Equity", "CLP"}
        }
    ),
    
    // Convertir tipos de datos
    #"Changed Types" = Table.TransformColumnTypes(Source,{
        {"PshipID", Int64.Type},
        {"FundName", type text},
        {"TotalAssets", Currency.Type},
        {"YTDReturn", Percentage.Type},
        {"Status", type text},
        {"RiskLevel", type text},
        {"AssetClass", type text},
        {"Currency", type text}
    }),
    
    // Agregar columnas calculadas
    #"Added AUM Billions" = Table.AddColumn(#"Changed Types", "AUM_Billions", 
        each [TotalAssets] / 1000000000, Currency.Type),
    
    #"Added Risk Category" = Table.AddColumn(#"Added AUM Billions", "RiskCategory", 
        each if [RiskLevel] = "Low" then "Low Risk" 
             else if [RiskLevel] = "Medium" then "Medium Risk" 
             else "High Risk"),
             
    #"Added Return Category" = Table.AddColumn(#"Added Risk Category", "ReturnCategory",
        each if [YTDReturn] < 0 then "Negative"
             else if [YTDReturn] < 0.05 then "Below 5%"
             else if [YTDReturn] < 0.15 then "5%-15%"
             else "Above 15%"),
             
    #"Added Performance Status" = Table.AddColumn(#"Added Return Category", "Performance", 
        each if [YTDReturn] >= 0.15 then "Excellent"
             else if [YTDReturn] >= 0.08 then "Good"
             else if [YTDReturn] >= 0.03 then "Average"
             else "Poor")
in
    #"Added Performance Status"

// =================================
// QUERY PARA KPIs DEMO
// =================================
/*
let
    Source = #table(
        {"KPI_Name", "Value", "Format_Type", "Description"},
        {
            {"Total AUM", 52500000000, "Currency", "Total Assets Under Management"},
            {"Average Return", 0.089, "Percentage", "Average YTD Return"},
            {"Active Funds", 15, "Number", "Number of Active Funds"},
            {"Top Fund Return", 0.245, "Percentage", "Best Performing Fund"},
            {"Risk Score", 2.6, "Number", "Portfolio Risk Score (1-5)"}
        }
    ),
    
    #"Changed Type" = Table.TransformColumnTypes(Source,{
        {"KPI_Name", type text},
        {"Value", type number},
        {"Format_Type", type text},
        {"Description", type text}
    })
in
    #"Changed Type"
*/

// =================================
// INSTRUCCIONES DE USO:
// =================================
/*
MÉTODO SIN SERVIDOR - DATOS DEMO:

1. PowerBI Desktop → Obtener datos → Consulta en blanco
2. Editor avanzado → Pegar el código de arriba
3. Nombre: "Funds Overview Demo"
4. Repetir para KPIs usando segundo código
5. Cerrar y aplicar

VENTAJAS:
- Funciona sin servidor
- Datos realistas para practicar
- Todas las funcionalidades de PowerBI disponibles
- Estructura idéntica al sistema real

DASHBOARD A CREAR:
- KPI Cards: Total AUM, Avg Return, Active Funds
- Table: Lista de fondos con filtros
- Pie Chart: Distribución por AssetClass
- Bar Chart: Performance por fondo
- Slicer: Risk Level, Asset Class

¡Practica el dashboard con estos datos y luego conectamos al servidor real!
*/