// =================================
// QUERY SIMPLIFICADA PARA POWERBI DESKTOP
// Copiar y pegar en Editor Avanzado
// =================================

let
    // Conectar al endpoint principal
    Source = Json.Document(Web.Contents("http://localhost:8000/api/v1/powerbi/funds")),
    
    // Convertir a tabla (manejo robusto de diferentes formatos)
    ConvertedToTable = if Value.Is(Source, type list) then 
                          Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error)
                       else 
                          Table.FromRecords({Source}),
    
    // Obtener nombres de campos disponibles dinámicamente  
    SampleRecord = if Value.Is(Source, type list) and List.Count(Source) > 0 then 
                      Source{0}
                   else if Value.Is(Source, type record) then
                      Source  
                   else
                      [],
                      
    FieldNames = Record.FieldNames(SampleRecord),
    
    // Expandir campos disponibles
    ExpandedData = if Value.Is(Source, type list) then
                      Table.ExpandRecordColumn(ConvertedToTable, "Column1", FieldNames)
                   else
                      ConvertedToTable,
    
    // Convertir tipos básicos de forma segura
    TypedData = Table.TransformColumnTypes(ExpandedData, {
        {"PshipID", Int64.Type},
        {"FundName", type text},
        {"Status", type text}
    }),
    
    // Agregar cálculos seguros
    FinalData = Table.AddColumn(TypedData, "AUM_Display", 
        each try 
            if Record.HasFields(_, "TotalAssets") then 
                Number.ToText([TotalAssets] / 1000000, "N0") & " M CLP"
            else 
                "N/A"
        otherwise "N/A"
    )
in
    FinalData

// =================================
// INSTRUCCIONES DE USO:
// =================================
/*
1. En PowerBI Desktop → Obtener datos → Web
2. URL: http://localhost:8000/api/v1/powerbi/funds
3. Transformar datos → Editor avanzado  
4. Pegar este código
5. Listo → Cerrar y aplicar

Esta query es robusta y se adapta automáticamente
a diferentes estructuras de respuesta del servidor.
*/