// PowerBI Queries para Investment Data Analysis Agent - ENDPOINTS ORIGINALES
// Copiar y pegar en PowerBI Desktop -> Transformar Datos -> Nueva Consulta -> Consulta en Blanco

// =================================
// QUERY 1: FUNDS OVERVIEW (Principal - ORIGINAL)
// =================================
let
    // Conectar a API original
    Source = Json.Document(Web.Contents("http://localhost:8000/api/v1/powerbi/funds")),
    
    // Extraer array de datos (estructura del endpoint real)
    data = Source,
    
    // Si viene en formato array, usar eso; sino, crear tabla directo
    #"Data Source" = if Value.Is(data, type list) then
                        Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error)
                     else  
                        Table.FromRecords({data}),
    
    // Expandir todas las columnas del endpoint real
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Data Source", 
        if Value.Is(data, type list) then "Column1" else "column",
        {"PshipID", "FundName", "Status", "TotalAssets", "YTDReturn", 
         "RiskLevel", "AssetClass", "Currency", "LastUpdated"}),
    
    // Convertir tipos de datos
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{
        {"PshipID", Int64.Type},
        {"FundName", type text},
        {"FundType", type text},
        {"TotalAssets", Currency.Type},
        {"YTDReturn", Percentage.Type},
        {"Benchmark", type text},
        {"RiskLevel", Int64.Type},
        {"Currency", type text},
        {"InceptionDate", type date},
        {"Status", type text}
    }),
    
    // Agregar columnas calculadas
    #"Added AUM Billions" = Table.AddColumn(#"Changed Type", "AUM_Billions", 
        each [TotalAssets] / 1000000000, Currency.Type),
    
    #"Added Risk Category" = Table.AddColumn(#"Added AUM Billions", "RiskCategory", 
        each if [RiskLevel] <= 2 then "Low Risk" 
             else if [RiskLevel] = 3 then "Medium Risk" 
             else "High Risk"),
             
    #"Added Return Category" = Table.AddColumn(#"Added Risk Category", "ReturnCategory",
        each if [YTDReturn] < 0 then "Negative"
             else if [YTDReturn] < 0.05 then "Below 5%"
             else if [YTDReturn] < 0.15 then "5%-15%"
             else "Above 15%")
in
    #"Added Return Category"

// =================================
// QUERY 2: KPIs DASHBOARD (ORIGINAL)
// =================================
let
    Source = Json.Document(Web.Contents("http://localhost:8000/api/v1/kpis/dashboard")),
    
    // Extraer métricas del endpoint real
    kpis = Source,
    
    // Crear tabla con estructura adaptada a respuesta real
    KPITable = if Record.HasFields(kpis, "total_aum") then
        #table(
            {"KPI_Name", "Value", "Format_Type"},
            {
                {"Total AUM", kpis[total_aum], "Currency"},
                {"Average Return", kpis[avg_return], "Percentage"}, 
                {"Active Funds", kpis[active_funds], "Number"},
                {"Top Fund", kpis[top_fund_return], "Percentage"}
            }
        )
    else
        // Fallback si la estructura es diferente
        Record.ToTable(kpis),
    
    #"Changed Type" = Table.TransformColumnTypes(KPITable,{
        {"Value", type number}
    })
in
    #"Changed Type"

// =================================
// QUERY 3: FUND DETAILS ALL (ORIGINAL)
// =================================
let
    Source = Json.Document(Web.Contents("http://localhost:8000/api/v1/powerbi/fund-details-all")),
    
    // Usar datos directamente del endpoint
    data = Source,
    
    // Convertir a tabla
    #"Data Table" = if Value.Is(data, type list) then 
                       Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error)
                    else
                       Table.FromRecords({data}),
    
    // Expandir campos disponibles
    #"Expanded Details" = if Value.Is(data, type list) then
                            Table.ExpandRecordColumn(#"Data Table", "Column1", 
                                Table.ColumnNames(Table.FromRecords({data{0}?})))
                         else
                            #"Data Table",
    
    #"Changed Type" = #"Expanded Details"
in
    #"Changed Type"

// =================================
// QUERY 4: FUND POSITIONS (ORIGINAL - Con Parámetro)
// =================================
// Nota: Crear parámetro "SelectedFundID" = 1 primero
let
    // Usar parámetro para Fund ID dinámico
    FundID = SelectedFundID,
    
    Source = Json.Document(Web.Contents("http://localhost:8000/api/v1/powerbi/fund-positions/" & Number.ToText(FundID))),
    
    // Usar datos directamente del endpoint real
    positions = if Record.HasFields(Source, "positions") then Source[positions] else Source,
    
    #"Converted to Table" = if Value.Is(positions, type list) then 
                              Table.FromList(positions, Splitter.SplitByNothing(), null, null, ExtraValues.Error)
                           else
                              Table.FromRecords({positions}),
    
    // Expandir campos disponibles en endpoint real
    AvailableFields = Table.ColumnNames(Table.FromRecords({positions{0}?})),
    
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", 
        if Value.Is(positions, type list) then "Column1" else "Column1",
        AvailableFields),
    
    // Convertir tipos básicos
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{
        {"PshipID", Int64.Type}
    })
in
    #"Changed Type"

// =================================
// PARÁMETROS A CREAR
// =================================
/*
1. Crear parámetro "SelectedFundID":
   - Tipo: Número entero
   - Valor actual: 1
   - Valores sugeridos: Usar valores de PshipID disponibles

2. URLs Base ORIGINALES:
   - Base: "http://localhost:8000/api/v1"
   - PowerBI: "http://localhost:8000/api/v1/powerbi"  
   - KPIs: "http://localhost:8000/api/v1/kpis"
*/

// =================================
// MEDIDAS DAX RECOMENDADAS (ORIGINALES)
// =================================
/*
// Total AUM
Total AUM = SUM('Funds Overview'[TotalAssets])

// Average Return  
Avg Return = AVERAGE('Funds Overview'[YTDReturn])

// Count Active Funds  
Active Funds = COUNTROWS(FILTER('Funds Overview', 'Funds Overview'[Status] = "Active"))

// Top Performer
Top Fund Return = MAX('Funds Overview'[YTDReturn])

// Risk Distribution
Risk Distribution = 
SWITCH(
    TRUE(),
    'Funds Overview'[RiskLevel] = "Low", "Low Risk",
    'Funds Overview'[RiskLevel] = "Medium", "Medium Risk", 
    'Funds Overview'[RiskLevel] = "High", "High Risk",
    "Other"
)
*/

// =================================
// INSTRUCCIONES POWERBI DESKTOP
// =================================
/*
PASO 1: Configurar conexiones
- Obtener Datos → Web
- URL: http://localhost:8000/api/v1/powerbi/funds
- Autenticación: Anónima

PASO 2: Crear queries adicionales  
- Nueva Consulta → Copiar código de QUERY 2, 3, 4
- Configurar parámetro SelectedFundID

PASO 3: Crear relaciones
- Usar PshipID como clave principal
- Crear drill-down entre tablas

PASO 4: Construir dashboard
- Tabla principal: Funds Overview
- KPI Cards: Del endpoint /kpis/dashboard  
- Drill-down: A posiciones por fondo

NOTA: El servidor debe estar ejecutándose en localhost:8000
Comando: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
*/